### model
model_name_or_path: aochongoliverli/Qwen2.5-3B-Zero-Base

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: ./data
dataset: math8k-sft-QwQ-32B-reasoning-traces
template: qwen25_zero_base
cutoff_len: 9216
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: ./outputs/math8k/Qwen2.5-3B-Zero-Base-math8k-sft-distill-20epochs-5e-5lr
logging_steps: 1
save_steps: 50
plot_loss: true

### train
# Effective batch size = per_device_train_batch_size * gradient_accumulation_steps * num_gpus = 2 * 8 * 4 = 128
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 5.0e-5
num_train_epochs: 20
lr_scheduler_type: cosine
warmup_ratio: 0.01
weight_decay: 0.0
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: Qwen2.5-3B-Zero-Base-math8k-sft-distill-20epochs-5e-5lr

