models:
  # RL
  ## stage 0: DeepMath SFT on Level 1-4
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-200"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step200"
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-400"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step400"
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-600"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step600"
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-800"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step800"
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-1000"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step1000"
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-1200"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step1200"
  # - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-1400"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step1400"
  - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-1600"
    nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step1600"
  - model_name: "aochongoliverli/Qwen2.5-1.5B-DeepMath-level1-4-40k-all_rollouts-sft-stage0-step-1890"
    nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-sft-stage0-step1890"