models:
  ## stage 0: CountDown Distilled model
  - model_name: "aochongoliverli/Qwen2.5-3B-sft-distill-countdown-level3-4-150"
    nick_name: "Qwen2.5-3B-distill-countdown-level3-4-1epoch-stage0"

  # - model_name: "aochongoliverli/Qwen2.5-3B-sft-distill-countdown-level3-4-300"
  #   nick_name: "Qwen2.5-3B-distill-countdown-level3-4-2epoch"

  # - model_name: "aochongoliverli/Qwen2.5-3B-sft-distill-countdown-level3-4-441"
  #   nick_name: "Qwen2.5-3B-distill-countdown-level3-4-3epoch"

  ## stage 1:CountDown RL from 1 epoch Distilled model
  - model_name: "aochongoliverli/Qwen2.5-3B-countdown-level4-5-grpo-20k-1epoch"
    nick_name: "Qwen2.5-3B-grpo-countdown-level4-5-1epoch-stage1"

  ## stage 2: CountDown RL on level 5
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2/global_step_50/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-stage2-50steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2/global_step_100/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-stage2-100steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2/global_step_150/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-stage2-150steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2/global_step_200/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-stage2-200steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2/global_step_250/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-stage2-250steps"

  ## stage 2: CountDown RL on level 5 with random thoughts
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2-randomthoughts/global_step_50/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-stage2-50steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2-randomthoughts/global_step_100/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-stage2-100steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2-randomthoughts/global_step_150/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-stage2-150steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2-randomthoughts/global_step_200/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-stage2-200steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-2epochs-4rollouts-8192max-length-stage2-randomthoughts/global_step_250/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-stage2-250steps"

  # stage 2: CountDown RL on level 5 with random thoughts only
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_50/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-50steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_100/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-100steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_150/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-150steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_200/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-200steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_250/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-250steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_300/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-300steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_350/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-350steps"
  - model_name: "/mnt/home/al2644/research/projects/rlvr/outputs/countdown/Qwen2.5-3B-countdown-level-5-4epochs-4rollouts-8192max-length-stage2-randomthoughts-only/global_step_400/actor"
    nick_name: "Qwen2.5-3B-countdown-level5-random_thought-only-stage2-400steps"


  ### DeepMath
  # Stage 0: SFT on DeepMath Level < 5
  # - model_name: "/mnt/home/al2644/research/projects/rlvr/sft/LLaMA-Factory/outputs/deepmath/Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0/checkpoint-100"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0-1epoch"
  # - model_name: "/mnt/home/al2644/research/projects/rlvr/sft/LLaMA-Factory/outputs/deepmath/Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0/checkpoint-200"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0-2epoch"
  # - model_name: "/mnt/home/al2644/research/projects/rlvr/sft/LLaMA-Factory/outputs/deepmath/Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0/checkpoint-300"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0-3epoch"
  # - model_name: "/mnt/home/al2644/research/projects/rlvr/sft/LLaMA-Factory/outputs/deepmath/Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0/checkpoint-400"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0-4epoch"
  # - model_name: "/mnt/home/al2644/research/projects/rlvr/sft/LLaMA-Factory/outputs/deepmath/Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0/checkpoint-525"
  #   nick_name: "Qwen2.5-1.5B-DeepMath-level1-4-14k-sft-stage0-5epoch"