### model
model_name_or_path: Qwen/Qwen2.5-3B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: ./data
dataset: limo-16k-reasoning-traces
template: qwen25_no_system_prompt
cutoff_len: 16640
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: /share/goyal/lio/reasoning/model/sft/math8k/Qwen2.5-3B-limo-16k-50epochs-5e-5lr-first50steps
logging_steps: 1
save_steps: 10
plot_loss: true

### train
# Effective batch size = per_device_train_batch_size * gradient_accumulation_steps * num_gpus = 1 * 32 * 2 = 64
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
learning_rate: 5.0e-5
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0.01
weight_decay: 0.0
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: Qwen2.5-3B-limo-16k-50epochs-5e-5lr-first50steps
